name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
# projects: ["octo-org/1", "octo-org/44"]
assignees:
  - noidilin
body:
  - type: markdown
    attributes:
      value: |
        This issue report is for learning purpose.
  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: What did you expect to happen?
      placeholder: Describe the problem in detail, including any error messages or unexpected behavior.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox Dev
        - Firefox
        - Zen
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: instruction
    attributes:
      label: Steps to reproduce
      description: What did you do leading up to the issue?
      placeholder: Please provide instruction to reproduce the issue, including environment setup and project state.
    validations:
      required: true
  - type: textarea
    id: fix_attempt
    attributes:
      label: What have you tried?
      description: list what you've already done to attempt to fix the issue.
      value: |
        1. 
        2. 
        3. 
        ...
  - type: textarea
    id: next_step
    attributes:
      label: Next step
      description: Outline what you plan to do next or waht information you need to continue.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
